DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS HEAD;
CREATE TABLE EMPLOYEE (
ID INT AUTO_INCREMENT  PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
SALARY VARCHAR(50) NOT NULL
);
CREATE TABLE HEAD (
ID INT AUTO_INCREMENT  PRIMARY KEY,
TITTLE VARCHAR(50) NOT NULL
);