DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS HEAD;
DROP TABLE IF EXISTS PATIENT;

CREATE TABLE EMPLOYEE (
ID INT AUTO_INCREMENT  PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
SALARY VARCHAR(50) NOT NULL
);
CREATE TABLE HEAD (
ID INT AUTO_INCREMENT  PRIMARY KEY,
TITTLE VARCHAR(50) NOT NULL
);
CREATE TABLE PATIENT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    BIRTHDATE VARCHAR(50) NOT NULL,
    GENDER VARCHAR(50) NOT NULL,
    DNI VARCHAR(50) NOT NULL,
    HABITUAL_RESIDENCE VARCHAR(50) NOT NULL,
    POPULATION_PROVINCE VARCHAR(50) NOT NULL,
    PROVINCE VARCHAR(50) NOT NULL,
    CLINICAL_RECORD_NUMBER VARCHAR(50) NOT NULL
);